export { default as BBECircle } from '../../public/images/bbe-circle.png';
export { default as ErinImage } from '../../public/images/erin.webp';
export { default as F1Header } from '../../public/images/f1-header.jpg';
export { default as JakobImage } from '../../public/images/jakob.webp';
export { default as JustineImage } from '../../public/images/justine.webp';
export { default as LeagueOfLegendsHeader } from '../../public/images/lol-header.jpeg';
export { default as MarliesImage } from '../../public/images/marlies.webp';
export { default as OverwatchHeader } from '../../public/images/ow-header.webp';
export { default as PlayerImage } from '../../public/images/player.webp';
