name: Deploy Preview

on:
  push:
    branches: [main]
    paths: ['apps/**', libs/**]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: https://preview.bbesports.de/
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.SSH_TARGET }}
            git pull
            bash ./tools/deploy.sh preview
